[0m13:16:30.989941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793f91f03fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793f904df760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793f904df700>]}


============================== 13:16:30.992633 | 15a83bcd-1401-4d30-b347-1a0e83816156 ==============================
[0m13:16:30.992633 [info ] [MainThread]: Running with dbt=1.8.9
[0m13:16:30.993251 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:16:31.006875 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/home/vscode/.dbt')}
[0m13:16:31.007671 [info ] [MainThread]: Creating dbt configuration folder at 
[0m13:23:46.140532 [debug] [MainThread]: Starter project path: /home/vscode/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m13:23:46.147457 [info ] [MainThread]: 
Your new dbt project "coffee_shop_louissa" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:23:46.148348 [info ] [MainThread]: Setting up your profile.
[0m13:25:34.855390 [info ] [MainThread]: Profile coffee_shop_louissa written to /home/vscode/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:25:34.856997 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 543.9114, "process_in_blocks": "736", "process_kernel_time": 0.139591, "process_mem_max_rss": "201244", "process_out_blocks": "88", "process_user_time": 1.570181}
[0m13:25:34.857701 [debug] [MainThread]: Command `dbt init` succeeded at 13:25:34.857579 after 543.91 seconds
[0m13:25:34.858141 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793f91f03fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793f904df730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793f904dff70>]}
[0m13:25:34.858570 [debug] [MainThread]: Flushing usage events
[0m11:31:47.730473 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b961a987e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b9618fac7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b9618fac850>]}


============================== 11:31:47.735737 | b55e28ab-caf5-49ea-9698-21c2ea417e9d ==============================
[0m11:31:47.735737 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:31:47.736566 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:31:47.737343 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:31:47.738834 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.053731598, "process_in_blocks": "68336", "process_kernel_time": 0.149653, "process_mem_max_rss": "85316", "process_out_blocks": "24", "process_user_time": 1.136556}
[0m11:31:47.739535 [debug] [MainThread]: Command `dbt run` failed at 11:31:47.739427 after 0.05 seconds
[0m11:31:47.739952 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b961a987e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b9618fac7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b9618fac100>]}
[0m11:31:47.740357 [debug] [MainThread]: Flushing usage events
[0m16:00:21.731223 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ce7073bdc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ce6ed18880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ce6ed188e0>]}


============================== 16:00:21.735120 | 97537919-1c95-447b-a102-b1d3dc46cded ==============================
[0m16:00:21.735120 [info ] [MainThread]: Running with dbt=1.8.9
[0m16:00:21.735843 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:00:21.736402 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:00:21.737700 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05216583, "process_in_blocks": "58624", "process_kernel_time": 0.132673, "process_mem_max_rss": "85604", "process_out_blocks": "8", "process_user_time": 1.097567}
[0m16:00:21.738336 [debug] [MainThread]: Command `dbt run` failed at 16:00:21.738238 after 0.05 seconds
[0m16:00:21.738726 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ce7073bdc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ce6ed18880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79ce6ed18220>]}
[0m16:00:21.739137 [debug] [MainThread]: Flushing usage events
[0m16:11:40.401180 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x6ffdc26afe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x6ffdc2a7b700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x6ffdc2a7b6a0>]}


============================== 16:11:40.403775 | bf1ec0ba-e0fd-4e71-acdc-cefa7869364b ==============================
[0m16:11:40.403775 [info ] [MainThread]: Running with dbt=1.8.9
[0m16:11:40.404481 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init demo-dbt-project', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:12:18.675610 [debug] [MainThread]: Starter project path: /home/vscode/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m16:12:18.682838 [info ] [MainThread]: 
Your new dbt project "demo_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:12:18.683444 [info ] [MainThread]: Setting up your profile.
[0m11:57:28.375834 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7adee1a67df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7adee1e3b970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7adee1e3b910>]}


============================== 11:57:28.380958 | 0d995516-3654-4b2d-99c4-ccd7c1c5fd81 ==============================
[0m11:57:28.380958 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:57:28.383400 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt docs generate', 'send_anonymous_usage_stats': 'True'}
[0m11:57:28.384508 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:57:28.385979 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.055633802, "process_in_blocks": "68336", "process_kernel_time": 0.112751, "process_mem_max_rss": "85384", "process_out_blocks": "8", "process_user_time": 1.12349}
[0m11:57:28.387098 [debug] [MainThread]: Command `dbt docs generate` failed at 11:57:28.386941 after 0.06 seconds
[0m11:57:28.387705 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7adee1a67df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7adee1e3b970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7adee1e3b640>]}
[0m11:57:28.388334 [debug] [MainThread]: Flushing usage events
[0m13:15:24.084797 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74d31673fe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74d314d27730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74d314d276d0>]}


============================== 13:15:24.090850 | 6286a742-5f70-4ebb-9045-da8090d37a36 ==============================
[0m13:15:24.090850 [info ] [MainThread]: Running with dbt=1.8.9
[0m13:15:24.092002 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init demo_dbt_project', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:15:24.108214 [info ] [MainThread]: A project called demo_dbt_project already exists here.
[0m13:15:24.109998 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.07691064, "process_in_blocks": "68712", "process_kernel_time": 0.161277, "process_mem_max_rss": "85848", "process_out_blocks": "8", "process_user_time": 1.266616}
[0m13:15:24.110796 [debug] [MainThread]: Command `dbt init` succeeded at 13:15:24.110656 after 0.08 seconds
[0m13:15:24.111235 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74d31673fe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74d314cfb7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74d314d240d0>]}
[0m13:15:24.111683 [debug] [MainThread]: Flushing usage events
[0m14:09:22.830117 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1e3e0beb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1e2443a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1e24439d0>]}


============================== 14:09:22.833153 | 037c7c28-51c7-4e1b-a596-d0c4fc304451 ==============================
[0m14:09:22.833153 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:09:22.833929 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt docs generate', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:09:22.834490 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:09:22.835471 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.051189493, "process_in_blocks": "0", "process_kernel_time": 0.063752, "process_mem_max_rss": "85540", "process_out_blocks": "16", "process_user_time": 1.155512}
[0m14:09:22.836230 [debug] [MainThread]: Command `dbt docs generate` failed at 14:09:22.836117 after 0.05 seconds
[0m14:09:22.836642 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1e3e0beb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1e2443a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1e2443640>]}
[0m14:09:22.837053 [debug] [MainThread]: Flushing usage events
[0m14:10:04.126305 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e3200efdc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e31e723820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e31e7237c0>]}


============================== 14:10:04.129322 | 9174c54b-0c29-4fc4-82d5-148a6cf41d2c ==============================
[0m14:10:04.129322 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:10:04.130090 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt docs serve', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:10:04.130650 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:10:04.131543 [debug] [MainThread]: Resource report: {"command_name": "serve", "command_success": false, "command_wall_clock_time": 0.051223613, "process_in_blocks": "0", "process_kernel_time": 0.055936, "process_mem_max_rss": "85836", "process_out_blocks": "8", "process_user_time": 1.106582}
[0m14:10:04.132262 [debug] [MainThread]: Command `dbt docs serve` failed at 14:10:04.132153 after 0.05 seconds
[0m14:10:04.132649 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e3200efdc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e31e723820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e31e723e80>]}
[0m14:10:04.133045 [debug] [MainThread]: Flushing usage events
[0m11:23:28.526049 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd33fd93e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd33e37b880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd33e37b820>]}


============================== 11:23:28.528511 | 9d3bf179-2fa0-4e30-8623-a8e5b365605d ==============================
[0m11:23:28.528511 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:23:28.529211 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:23:28.529759 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:23:28.530583 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.047319345, "process_in_blocks": "0", "process_kernel_time": 0.079899, "process_mem_max_rss": "85504", "process_out_blocks": "16", "process_user_time": 1.098621}
[0m11:23:28.531161 [debug] [MainThread]: Command `dbt test` failed at 11:23:28.531056 after 0.05 seconds
[0m11:23:28.531533 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd33fd93e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd33e37b880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd33e37bee0>]}
[0m11:23:28.531913 [debug] [MainThread]: Flushing usage events
[0m12:29:21.282641 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70809944fe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x708097a7f8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x708097a7f850>]}


============================== 12:29:21.285188 | 06bfec08-5648-4b9b-8222-08d62a88e834 ==============================
[0m12:29:21.285188 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:29:21.285924 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:29:21.286444 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:29:21.287247 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.048652135, "process_in_blocks": "0", "process_kernel_time": 0.0554, "process_mem_max_rss": "85844", "process_out_blocks": "8", "process_user_time": 1.100101}
[0m12:29:21.287832 [debug] [MainThread]: Command `dbt test` failed at 12:29:21.287729 after 0.05 seconds
[0m12:29:21.288219 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70809944fe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x708097a7f8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x708097a7ff10>]}
[0m12:29:21.288607 [debug] [MainThread]: Flushing usage events
[0m12:36:33.908367 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b7057fcbe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b70565f87c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b70565f8820>]}


============================== 12:36:33.912462 | d3b3924a-07b4-4466-8d9d-2b4a3251a6b8 ==============================
[0m12:36:33.912462 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:36:33.913401 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt test', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:36:33.914656 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:36:33.916296 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.0574671, "process_in_blocks": "0", "process_kernel_time": 0.071876, "process_mem_max_rss": "85740", "process_out_blocks": "8", "process_user_time": 1.045652}
[0m12:36:33.917109 [debug] [MainThread]: Command `dbt test` failed at 12:36:33.916974 after 0.06 seconds
[0m12:36:33.917661 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b7057fcbe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b70565f87c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b70565f8160>]}
[0m12:36:33.918140 [debug] [MainThread]: Flushing usage events
[0m10:36:09.289314 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dbeec1e7e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dbeea814730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dbeea814790>]}


============================== 10:36:09.293454 | a87282f1-dd81-49a2-a56f-609e2478317c ==============================
[0m10:36:09.293454 [info ] [MainThread]: Running with dbt=1.8.9
[0m10:36:09.294564 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt test --select customers', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:36:09.295215 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:36:09.296523 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.052427255, "process_in_blocks": "68240", "process_kernel_time": 0.142403, "process_mem_max_rss": "85484", "process_out_blocks": "8", "process_user_time": 1.143185}
[0m10:36:09.297167 [debug] [MainThread]: Command `dbt test` failed at 10:36:09.297065 after 0.05 seconds
[0m10:36:09.297562 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dbeec1e7e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dbeea814730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dbeea8140d0>]}
[0m10:36:09.297951 [debug] [MainThread]: Flushing usage events
[0m12:02:29.470559 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dc5ed9cbfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dc5ec003910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dc5ec0038b0>]}


============================== 12:02:29.477065 | b81aa81b-54ac-40c5-b0c3-68ee5d522fb5 ==============================
[0m12:02:29.477065 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:02:29.477924 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt test --select source:coffee_shop_source.customers', 'send_anonymous_usage_stats': 'True'}
[0m12:02:29.478574 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:02:29.480134 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.05760799, "process_in_blocks": "59952", "process_kernel_time": 0.215156, "process_mem_max_rss": "85624", "process_out_blocks": "8", "process_user_time": 1.216614}
[0m12:02:29.480954 [debug] [MainThread]: Command `dbt test` failed at 12:02:29.480834 after 0.06 seconds
[0m12:02:29.481405 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dc5ed9cbfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dc5ec003910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dc5ec003f70>]}
[0m12:02:29.481855 [debug] [MainThread]: Flushing usage events
[0m12:07:51.278353 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ba28293ffa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ba280f778e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ba280f77880>]}


============================== 12:07:51.281443 | 580d97b1-926e-45fb-8861-998c1b605a39 ==============================
[0m12:07:51.281443 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:07:51.282199 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt test --select my_dbt_project', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:07:51.282782 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:07:51.283707 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.05053446, "process_in_blocks": "0", "process_kernel_time": 0.063837, "process_mem_max_rss": "85368", "process_out_blocks": "16", "process_user_time": 1.097209}
[0m12:07:51.284364 [debug] [MainThread]: Command `dbt test` failed at 12:07:51.284256 after 0.05 seconds
[0m12:07:51.284787 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ba28293ffa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ba280f778e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ba280f77f40>]}
[0m12:07:51.285204 [debug] [MainThread]: Flushing usage events
[0m16:24:49.885181 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x798adf71ffa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x798adfaef8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x798adfaef850>]}


============================== 16:24:49.890480 | bdc62f74-6065-4824-93ae-04f619e9f015 ==============================
[0m16:24:49.890480 [info ] [MainThread]: Running with dbt=1.8.9
[0m16:24:49.891649 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:24:49.892327 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:24:49.893709 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05358397, "process_in_blocks": "59528", "process_kernel_time": 0.17597, "process_mem_max_rss": "85348", "process_out_blocks": "8", "process_user_time": 1.084468}
[0m16:24:49.894397 [debug] [MainThread]: Command `dbt run` failed at 16:24:49.894293 after 0.05 seconds
[0m16:24:49.894784 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x798adf71ffa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x798adfaef8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x798adfaeff10>]}
[0m16:24:49.895215 [debug] [MainThread]: Flushing usage events
[0m17:18:24.407440 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74c018293eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74c0168cb8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74c0168cb850>]}


============================== 17:18:24.411665 | c4b346df-cf4f-49b7-97b5-e1b9d0410da6 ==============================
[0m17:18:24.411665 [info ] [MainThread]: Running with dbt=1.8.9
[0m17:18:24.412372 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:18:24.412908 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:18:24.414191 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.05138387, "process_in_blocks": "68064", "process_kernel_time": 0.138772, "process_mem_max_rss": "85288", "process_out_blocks": "16", "process_user_time": 1.122796}
[0m17:18:24.414887 [debug] [MainThread]: Command `dbt test` failed at 17:18:24.414780 after 0.05 seconds
[0m17:18:24.415271 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74c018293eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74c0168cb8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74c0168cbf10>]}
[0m17:18:24.415655 [debug] [MainThread]: Flushing usage events
[0m17:46:22.908886 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7ce833fe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7ce691c7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7ce691c820>]}


============================== 17:46:22.911511 | 01d09b02-cdf6-47e8-8a57-05f1e5a81030 ==============================
[0m17:46:22.911511 [info ] [MainThread]: Running with dbt=1.8.9
[0m17:46:22.912154 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:46:22.912654 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:46:22.913439 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.048146836, "process_in_blocks": "0", "process_kernel_time": 0.059671, "process_mem_max_rss": "85616", "process_out_blocks": "8", "process_user_time": 1.010437}
[0m17:46:22.914033 [debug] [MainThread]: Command `dbt run` failed at 17:46:22.913931 after 0.05 seconds
[0m17:46:22.914414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7ce833fe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7ce691c7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7ce691c160>]}
[0m17:46:22.914817 [debug] [MainThread]: Flushing usage events
[0m11:51:57.599142 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75e22625fdf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75e2266207f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75e226620850>]}


============================== 11:51:57.603785 | 8696b568-788d-4546-89a1-3b0c7b09cfee ==============================
[0m11:51:57.603785 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:51:57.604461 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:51:57.604994 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:51:57.606278 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.052057996, "process_in_blocks": "59064", "process_kernel_time": 0.134503, "process_mem_max_rss": "85284", "process_out_blocks": "8", "process_user_time": 1.190748}
[0m11:51:57.606999 [debug] [MainThread]: Command `dbt run` failed at 11:51:57.606893 after 0.05 seconds
[0m11:51:57.607389 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75e22625fdf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75e2266207f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75e226620190>]}
[0m11:51:57.607776 [debug] [MainThread]: Flushing usage events
[0m12:04:23.432334 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x778e885ebe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x778e86bc8760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x778e86bc87c0>]}


============================== 12:04:23.434901 | 70942b00-a1f3-41ed-aa88-88f5985daac9 ==============================
[0m12:04:23.434901 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:04:23.435561 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:04:23.436079 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:04:23.436857 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04775865, "process_in_blocks": "0", "process_kernel_time": 0.051911, "process_mem_max_rss": "85664", "process_out_blocks": "16", "process_user_time": 1.014278}
[0m12:04:23.437433 [debug] [MainThread]: Command `dbt run` failed at 12:04:23.437332 after 0.05 seconds
[0m12:04:23.437806 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x778e885ebe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x778e86bc8760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x778e86bc8100>]}
[0m12:04:23.438184 [debug] [MainThread]: Flushing usage events
[0m12:12:48.554363 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a5ebf24fdc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a5ebf610850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a5ebf6108b0>]}


============================== 12:12:48.556904 | 83ba747b-a37e-4506-a970-52eca330c91d ==============================
[0m12:12:48.556904 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:12:48.557571 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m12:12:48.558080 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:12:48.558891 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.047914486, "process_in_blocks": "0", "process_kernel_time": 0.059874, "process_mem_max_rss": "85524", "process_out_blocks": "8", "process_user_time": 1.007717}
[0m12:12:48.559474 [debug] [MainThread]: Command `dbt run` failed at 12:12:48.559373 after 0.05 seconds
[0m12:12:48.559859 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a5ebf24fdc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a5ebf610850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a5ebf6101f0>]}
[0m12:12:48.560245 [debug] [MainThread]: Flushing usage events
[0m12:13:39.177085 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796a4d7afe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796a4bd8c790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796a4bd8c7f0>]}


============================== 12:13:39.179724 | a602a326-b2a0-4111-a746-0abf5fd58337 ==============================
[0m12:13:39.179724 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:13:39.180380 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m12:13:39.180903 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:13:39.181729 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04848089, "process_in_blocks": "0", "process_kernel_time": 0.059761, "process_mem_max_rss": "85548", "process_out_blocks": "16", "process_user_time": 1.079683}
[0m12:13:39.182341 [debug] [MainThread]: Command `dbt run` failed at 12:13:39.182221 after 0.05 seconds
[0m12:13:39.182778 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796a4d7afe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796a4bd8c790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796a4bd8c130>]}
[0m12:13:39.183177 [debug] [MainThread]: Flushing usage events
[0m12:14:04.633963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73b736153e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73b734778760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73b7347787c0>]}


============================== 12:14:04.638177 | 1ea98a5b-5c7b-4238-9934-6cc95bc7e513 ==============================
[0m12:14:04.638177 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:14:04.639354 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:14:04.640200 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:14:04.641621 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07656561, "process_in_blocks": "0", "process_kernel_time": 0.056001, "process_mem_max_rss": "85496", "process_out_blocks": "8", "process_user_time": 1.100021}
[0m12:14:04.642541 [debug] [MainThread]: Command `dbt run` failed at 12:14:04.642400 after 0.08 seconds
[0m12:14:04.643397 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73b736153e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73b734778760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73b734778100>]}
[0m12:14:04.644247 [debug] [MainThread]: Flushing usage events
[0m12:14:25.496847 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73cb618dfe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73cb5ff0c7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73cb5ff0c820>]}


============================== 12:14:25.501212 | f9f9f950-8acc-456e-a05a-59e7a9ec2d80 ==============================
[0m12:14:25.501212 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:14:25.502155 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:14:25.503029 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:14:25.504262 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07949579, "process_in_blocks": "0", "process_kernel_time": 0.060042, "process_mem_max_rss": "85400", "process_out_blocks": "8", "process_user_time": 1.140815}
[0m12:14:25.505201 [debug] [MainThread]: Command `dbt run` failed at 12:14:25.505047 after 0.08 seconds
[0m12:14:25.505848 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73cb618dfe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73cb5ff0c7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73cb5ff0c160>]}
[0m12:14:25.506516 [debug] [MainThread]: Flushing usage events
[0m12:24:31.002539 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74942946be80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x749427aa38b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x749427aa3850>]}


============================== 12:24:31.005091 | 64a2c0d0-3dce-4362-aa07-77ab3bebba70 ==============================
[0m12:24:31.005091 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:24:31.005723 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:24:31.006219 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:24:31.007006 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.07373918, "process_in_blocks": "0", "process_kernel_time": 0.075714, "process_mem_max_rss": "85864", "process_out_blocks": "16", "process_user_time": 1.007094}
[0m12:24:31.007587 [debug] [MainThread]: Command `dbt test` failed at 12:24:31.007481 after 0.07 seconds
[0m12:24:31.007968 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74942946be80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x749427aa38b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x749427aa3f10>]}
[0m12:24:31.008343 [debug] [MainThread]: Flushing usage events
[0m12:28:12.852464 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f60895efe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6087c147c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6087c14820>]}


============================== 12:28:12.855043 | d0ab0073-763c-4e1a-8c69-5d30050472e4 ==============================
[0m12:28:12.855043 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:28:12.855693 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:28:12.856204 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:28:12.856984 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04914024, "process_in_blocks": "0", "process_kernel_time": 0.052109, "process_mem_max_rss": "85780", "process_out_blocks": "8", "process_user_time": 1.010128}
[0m12:28:12.857552 [debug] [MainThread]: Command `dbt run` failed at 12:28:12.857454 after 0.05 seconds
[0m12:28:12.857925 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f60895efe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6087c147c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6087c14160>]}
[0m12:28:12.858311 [debug] [MainThread]: Flushing usage events
[0m12:31:02.190600 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79da06e57eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79da05484730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79da05484790>]}


============================== 12:31:02.193117 | 64dd58c7-4994-4ae1-a9ad-97109347b648 ==============================
[0m12:31:02.193117 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:31:02.193759 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:31:02.194262 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:31:02.195053 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.047560148, "process_in_blocks": "0", "process_kernel_time": 0.05986, "process_mem_max_rss": "85640", "process_out_blocks": "16", "process_user_time": 1.040785}
[0m12:31:02.195598 [debug] [MainThread]: Command `dbt run` failed at 12:31:02.195500 after 0.05 seconds
[0m12:31:02.195980 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79da06e57eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79da05484730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79da054840d0>]}
[0m12:31:02.196363 [debug] [MainThread]: Flushing usage events
[0m12:31:26.497855 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7420a40f3d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7420a2718850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7420a27188b0>]}


============================== 12:31:26.500273 | 26c9fdac-da56-46e8-98b7-148252e0cc8d ==============================
[0m12:31:26.500273 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:31:26.500921 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:31:26.501421 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:31:26.502194 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.046936397, "process_in_blocks": "0", "process_kernel_time": 0.067995, "process_mem_max_rss": "85484", "process_out_blocks": "8", "process_user_time": 1.023925}
[0m12:31:26.502772 [debug] [MainThread]: Command `dbt run` failed at 12:31:26.502647 after 0.05 seconds
[0m12:31:26.503167 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7420a40f3d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7420a2718850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7420a27181f0>]}
[0m12:31:26.503559 [debug] [MainThread]: Flushing usage events
[0m10:04:31.920384 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75adcba77fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75adca0a78b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75adca0a7850>]}


============================== 10:04:31.925587 | 8f0222cf-5f7a-4188-b72a-8f50ff9e625f ==============================
[0m10:04:31.925587 [info ] [MainThread]: Running with dbt=1.8.9
[0m10:04:31.926327 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:04:31.926894 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:04:31.928326 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05304669, "process_in_blocks": "68056", "process_kernel_time": 0.177733, "process_mem_max_rss": "85264", "process_out_blocks": "8", "process_user_time": 1.180937}
[0m10:04:31.929021 [debug] [MainThread]: Command `dbt run` failed at 10:04:31.928913 after 0.05 seconds
[0m10:04:31.929433 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75adcba77fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75adca0a78b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75adca0a7f10>]}
[0m10:04:31.929855 [debug] [MainThread]: Flushing usage events
[0m12:49:54.567966 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x724088067e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x724086694760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7240866947c0>]}


============================== 12:49:54.574446 | cedfbb48-8c1d-4c7a-8259-7885db64b379 ==============================
[0m12:49:54.574446 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:49:54.575424 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:49:54.576222 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:49:54.577893 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.059246138, "process_in_blocks": "69336", "process_kernel_time": 0.170783, "process_mem_max_rss": "85492", "process_out_blocks": "16", "process_user_time": 1.195484}
[0m12:49:54.578722 [debug] [MainThread]: Command `dbt run` failed at 12:49:54.578606 after 0.06 seconds
[0m12:49:54.579141 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x724088067e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x724086694760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x724086694100>]}
[0m12:49:54.579598 [debug] [MainThread]: Flushing usage events
[0m14:15:16.493742 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c3063e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c16887c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c1688820>]}


============================== 14:15:16.499380 | 5ae30054-ab58-4817-87f3-87d3c477ea4b ==============================
[0m14:15:16.499380 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:15:16.500138 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt test', 'send_anonymous_usage_stats': 'True'}
[0m14:15:16.500683 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:15:16.501970 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.055042233, "process_in_blocks": "68136", "process_kernel_time": 0.149344, "process_mem_max_rss": "85460", "process_out_blocks": "8", "process_user_time": 1.150354}
[0m14:15:16.502602 [debug] [MainThread]: Command `dbt test` failed at 14:15:16.502500 after 0.06 seconds
[0m14:15:16.502975 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c3063e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c16887c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c1688160>]}
[0m14:15:16.503372 [debug] [MainThread]: Flushing usage events
[0m15:15:14.807050 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dd65dc07e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dd65c234790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dd65c2347f0>]}


============================== 15:15:14.812648 | 2a93ba60-e064-44e2-a7d2-7367a378b607 ==============================
[0m15:15:14.812648 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:15:14.813389 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:15:14.813934 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:15:14.815344 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.055693287, "process_in_blocks": "68432", "process_kernel_time": 0.083508, "process_mem_max_rss": "85256", "process_out_blocks": "16", "process_user_time": 1.220817}
[0m15:15:14.816038 [debug] [MainThread]: Command `dbt run` failed at 15:15:14.815926 after 0.06 seconds
[0m15:15:14.816451 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dd65dc07e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dd65c234790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7dd65c234130>]}
[0m15:15:14.816857 [debug] [MainThread]: Flushing usage events
[0m09:19:26.592583 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93c0063eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93be6407c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93be640820>]}


============================== 09:19:26.597958 | 10f3de23-bd21-4fca-8474-6c1503164adf ==============================
[0m09:19:26.597958 [info ] [MainThread]: Running with dbt=1.8.9
[0m09:19:26.598696 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:19:26.599212 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:19:26.600481 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05354581, "process_in_blocks": "68352", "process_kernel_time": 0.149653, "process_mem_max_rss": "85336", "process_out_blocks": "8", "process_user_time": 1.094835}
[0m09:19:26.601181 [debug] [MainThread]: Command `dbt run` failed at 09:19:26.601079 after 0.05 seconds
[0m09:19:26.601581 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93c0063eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93be6407c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93be640160>]}
[0m09:19:26.601986 [debug] [MainThread]: Flushing usage events
[0m10:17:16.097348 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7bf8193e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7bf677b700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7bf677b6a0>]}


============================== 10:17:16.099899 | 8678f89a-a419-4db6-b9dd-aafbda0504ec ==============================
[0m10:17:16.099899 [info ] [MainThread]: Running with dbt=1.8.9
[0m10:17:16.100598 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:17:16.101240 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:17:16.102041 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.04871649, "process_in_blocks": "0", "process_kernel_time": 0.091375, "process_mem_max_rss": "85548", "process_out_blocks": "8", "process_user_time": 1.048827}
[0m10:17:16.102646 [debug] [MainThread]: Command `dbt deps` failed at 10:17:16.102539 after 0.05 seconds
[0m10:17:16.103038 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7bf8193e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7bf677b940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e7bf677beb0>]}
[0m10:17:16.103429 [debug] [MainThread]: Flushing usage events
[0m11:33:59.314012 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74370de43df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74370c4687c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74370c468820>]}


============================== 11:33:59.316618 | 0e0e7920-7d71-4d13-91ea-c441d7e5a936 ==============================
[0m11:33:59.316618 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:33:59.317278 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt test --select mutually_exclusive_ranges', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:33:59.317802 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:33:59.318612 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.04890287, "process_in_blocks": "0", "process_kernel_time": 0.055789, "process_mem_max_rss": "85536", "process_out_blocks": "16", "process_user_time": 1.048039}
[0m11:33:59.319226 [debug] [MainThread]: Command `dbt test` failed at 11:33:59.319119 after 0.05 seconds
[0m11:33:59.319638 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74370de43df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74370c4687c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74370c468160>]}
[0m11:33:59.320035 [debug] [MainThread]: Flushing usage events
[0m12:18:34.944631 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x787399cabfa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873982db790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873982db730>]}


============================== 12:18:34.947216 | e6f8c3f8-747e-41fa-8085-d5785effbd06 ==============================
[0m12:18:34.947216 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:18:34.947866 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:18:34.948545 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:18:34.949363 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.048082225, "process_in_blocks": "0", "process_kernel_time": 0.051763, "process_mem_max_rss": "85640", "process_out_blocks": "8", "process_user_time": 1.106944}
[0m12:18:34.949963 [debug] [MainThread]: Command `dbt deps` failed at 12:18:34.949857 after 0.05 seconds
[0m12:18:34.950346 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x787399cabfa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873982db9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873982dbf40>]}
[0m12:18:34.950748 [debug] [MainThread]: Flushing usage events
[0m12:54:21.614925 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a51a2093d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a51a24548b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a51a2454910>]}


============================== 12:54:21.617519 | a168022b-8cd6-4c03-8b23-a8a9780bcfd0 ==============================
[0m12:54:21.617519 [info ] [MainThread]: Running with dbt=1.8.9
[0m12:54:21.618177 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m12:54:21.618704 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:54:21.619495 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.048588667, "process_in_blocks": "0", "process_kernel_time": 0.064332, "process_mem_max_rss": "85876", "process_out_blocks": "16", "process_user_time": 1.089627}
[0m12:54:21.620088 [debug] [MainThread]: Command `dbt run` failed at 12:54:21.619991 after 0.05 seconds
[0m12:54:21.620497 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a51a2093d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a51a24548b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a51a2454250>]}
[0m12:54:21.620881 [debug] [MainThread]: Flushing usage events
[0m13:29:44.055805 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x755308febe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7553075d3760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7553075d3700>]}


============================== 13:29:44.058387 | 833b715c-e267-429a-9a9d-b131eb202a2f ==============================
[0m13:29:44.058387 [info ] [MainThread]: Running with dbt=1.8.9
[0m13:29:44.059068 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:29:44.059705 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:29:44.060566 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.048087742, "process_in_blocks": "0", "process_kernel_time": 0.063715, "process_mem_max_rss": "85632", "process_out_blocks": "8", "process_user_time": 1.059268}
[0m13:29:44.061153 [debug] [MainThread]: Command `dbt deps` failed at 13:29:44.061047 after 0.05 seconds
[0m13:29:44.061541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x755308febe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7553075d39a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7553075d3f10>]}
[0m13:29:44.061934 [debug] [MainThread]: Flushing usage events
[0m15:23:30.806382 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d4f5a06be50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d4f58690790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d4f586907f0>]}


============================== 15:23:30.811233 | 58abb1d5-0fb1-416b-ae15-b4c1f75fdaea ==============================
[0m15:23:30.811233 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:23:30.812358 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:23:30.812917 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:23:30.814171 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.054182526, "process_in_blocks": "69240", "process_kernel_time": 0.164124, "process_mem_max_rss": "85312", "process_out_blocks": "8", "process_user_time": 1.124626}
[0m15:23:30.814896 [debug] [MainThread]: Command `dbt run` failed at 15:23:30.814789 after 0.06 seconds
[0m15:23:30.815284 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d4f5a06be50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d4f58690790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d4f58690130>]}
[0m15:23:30.815678 [debug] [MainThread]: Flushing usage events
[0m08:49:26.034929 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7599b129fe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7599b1660760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7599b16607c0>]}


============================== 08:49:26.039561 | 0af8d2bc-600f-46ad-83e4-ecb5f63c6930 ==============================
[0m08:49:26.039561 [info ] [MainThread]: Running with dbt=1.8.9
[0m08:49:26.040245 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m08:49:26.040797 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:49:26.042041 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05747332, "process_in_blocks": "68200", "process_kernel_time": 0.167111, "process_mem_max_rss": "85404", "process_out_blocks": "16", "process_user_time": 1.129993}
[0m08:49:26.042812 [debug] [MainThread]: Command `dbt run` failed at 08:49:26.042701 after 0.06 seconds
[0m08:49:26.043213 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7599b129fe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7599b1660760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7599b1660100>]}
[0m08:49:26.043604 [debug] [MainThread]: Flushing usage events
[0m09:58:29.832022 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dfd162be20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dfcfc13730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dfcfc136d0>]}


============================== 09:58:29.834489 | fdf41861-83d8-4cbd-af13-b9dbe18f3fd5 ==============================
[0m09:58:29.834489 [info ] [MainThread]: Running with dbt=1.8.9
[0m09:58:29.835131 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt deps', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:58:29.835744 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:58:29.836548 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.047116093, "process_in_blocks": "0", "process_kernel_time": 0.043867, "process_mem_max_rss": "85640", "process_out_blocks": "8", "process_user_time": 1.028886}
[0m09:58:29.837093 [debug] [MainThread]: Command `dbt deps` failed at 09:58:29.836990 after 0.05 seconds
[0m09:58:29.837471 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dfd162be20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dfcfc13970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dfcfc13ee0>]}
[0m09:58:29.837853 [debug] [MainThread]: Flushing usage events
[0m10:52:15.627006 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e39fbbbbe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e39fa1987c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e39fa198820>]}


============================== 10:52:15.631819 | 4cf044e8-cffe-4131-9521-a6bf401718bd ==============================
[0m10:52:15.631819 [info ] [MainThread]: Running with dbt=1.8.9
[0m10:52:15.632548 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m10:52:15.633080 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:52:15.634321 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.052645434, "process_in_blocks": "68352", "process_kernel_time": 0.17862, "process_mem_max_rss": "85500", "process_out_blocks": "16", "process_user_time": 1.103479}
[0m10:52:15.634961 [debug] [MainThread]: Command `dbt run` failed at 10:52:15.634855 after 0.05 seconds
[0m10:52:15.635356 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e39fbbbbe20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e39fa1987c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e39fa198160>]}
[0m10:52:15.635757 [debug] [MainThread]: Flushing usage events
[0m11:51:34.220919 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79a4603d3dc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79a460794850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79a4607948b0>]}


============================== 11:51:34.223540 | da5694cb-af00-458a-8ae8-cd454e801781 ==============================
[0m11:51:34.223540 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:51:34.224203 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:51:34.224716 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:51:34.225523 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.048562083, "process_in_blocks": "0", "process_kernel_time": 0.068083, "process_mem_max_rss": "85632", "process_out_blocks": "8", "process_user_time": 1.005227}
[0m11:51:34.226161 [debug] [MainThread]: Command `dbt run` failed at 11:51:34.226055 after 0.05 seconds
[0m11:51:34.226548 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79a4603d3dc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79a460794850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79a4607941f0>]}
[0m11:51:34.226952 [debug] [MainThread]: Flushing usage events
[0m11:56:57.177242 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75d20f7ebe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75d20ddc87f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75d20ddc8850>]}


============================== 11:56:57.179860 | b221bba1-9096-480b-b0c9-17b054550b1e ==============================
[0m11:56:57.179860 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:56:57.180528 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:56:57.181038 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:56:57.181870 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.048306294, "process_in_blocks": "0", "process_kernel_time": 0.087783, "process_mem_max_rss": "85652", "process_out_blocks": "8", "process_user_time": 1.001532}
[0m11:56:57.182473 [debug] [MainThread]: Command `dbt run` failed at 11:56:57.182367 after 0.05 seconds
[0m11:56:57.182861 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75d20f7ebe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75d20ddc87f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75d20ddc8190>]}
[0m11:56:57.183261 [debug] [MainThread]: Flushing usage events
[0m17:35:40.635001 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x733a727abdf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x733a70dd8820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x733a70dd8880>]}


============================== 17:35:40.644124 | c416e765-a77c-4798-a377-9b5f30a9756f ==============================
[0m17:35:40.644124 [info ] [MainThread]: Running with dbt=1.8.9
[0m17:35:40.646982 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:35:40.648142 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:35:40.650916 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.14080848, "process_in_blocks": "68904", "process_kernel_time": 0.293543, "process_mem_max_rss": "85548", "process_out_blocks": "16", "process_user_time": 1.483168}
[0m17:35:40.651829 [debug] [MainThread]: Command `dbt run` failed at 17:35:40.651643 after 0.14 seconds
[0m17:35:40.652463 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x733a727abdf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x733a70dd8820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x733a70dd81c0>]}
[0m17:35:40.653214 [debug] [MainThread]: Flushing usage events
[0m09:19:47.392534 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e447acd7eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e4479300730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e4479300790>]}


============================== 09:19:47.397382 | 83cb12a5-e15e-47b0-a425-f96bea08a309 ==============================
[0m09:19:47.397382 [info ] [MainThread]: Running with dbt=1.8.9
[0m09:19:47.398096 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m09:19:47.398715 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:19:47.400023 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.052013975, "process_in_blocks": "35656", "process_kernel_time": 0.123208, "process_mem_max_rss": "85456", "process_out_blocks": "8", "process_user_time": 1.073708}
[0m09:19:47.400717 [debug] [MainThread]: Command `dbt run` failed at 09:19:47.400609 after 0.05 seconds
[0m09:19:47.401153 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e447acd7eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e4479300730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e44793000d0>]}
[0m09:19:47.401583 [debug] [MainThread]: Flushing usage events
[0m19:55:28.918388 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x734b96803fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x734b94e2c760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x734b94e2c7c0>]}


============================== 19:55:28.922150 | b4469aed-a539-48eb-8c37-acc5bf703189 ==============================
[0m19:55:28.922150 [info ] [MainThread]: Running with dbt=1.8.9
[0m19:55:28.922943 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:55:28.923520 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:55:28.924383 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.049683675, "process_in_blocks": "16", "process_kernel_time": 0.087742, "process_mem_max_rss": "85480", "process_out_blocks": "16", "process_user_time": 1.03297}
[0m19:55:28.925032 [debug] [MainThread]: Command `dbt run` failed at 19:55:28.924923 after 0.05 seconds
[0m19:55:28.925488 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x734b96803fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x734b94e2c760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x734b94e2c100>]}
[0m19:55:28.925945 [debug] [MainThread]: Flushing usage events
[0m14:06:17.955837 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aef0f867e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aef0de90760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aef0de907c0>]}


============================== 14:06:17.960938 | 68b1c3c1-aed2-4e22-bc15-d75ee8c34e98 ==============================
[0m14:06:17.960938 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:06:17.961750 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:06:17.962313 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:06:17.963205 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05243499, "process_in_blocks": "28584", "process_kernel_time": 0.101503, "process_mem_max_rss": "85496", "process_out_blocks": "8", "process_user_time": 1.079996}
[0m14:06:17.963862 [debug] [MainThread]: Command `dbt run` failed at 14:06:17.963731 after 0.05 seconds
[0m14:06:17.964282 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aef0f867e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aef0de90760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aef0de90100>]}
[0m14:06:17.964708 [debug] [MainThread]: Flushing usage events
[0m15:43:15.765573 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77a878c43fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77a877274760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77a8772747c0>]}


============================== 15:43:15.768105 | 91cde19e-8f5b-430a-b3b9-6ca28837fefd ==============================
[0m15:43:15.768105 [info ] [MainThread]: Running with dbt=1.8.9
[0m15:43:15.768800 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:43:15.769329 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:43:15.770164 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.047604527, "process_in_blocks": "0", "process_kernel_time": 0.051881, "process_mem_max_rss": "85392", "process_out_blocks": "8", "process_user_time": 1.06955}
[0m15:43:15.770746 [debug] [MainThread]: Command `dbt run` failed at 15:43:15.770645 after 0.05 seconds
[0m15:43:15.771132 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77a878c43fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77a877274760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77a877274100>]}
[0m15:43:15.771527 [debug] [MainThread]: Flushing usage events
[0m11:31:07.941411 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d0345f43e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d03447ec8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d03447ec910>]}


============================== 11:31:07.947063 | 15ce2d18-7bcd-4ae5-a040-f9e3a19bd83a ==============================
[0m11:31:07.947063 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:31:07.947925 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:31:07.959942 [info ] [MainThread]: dbt version: 1.8.9
[0m11:31:07.960529 [info ] [MainThread]: python version: 3.10.12
[0m11:31:07.961014 [info ] [MainThread]: python path: /usr/bin/python3
[0m11:31:07.961445 [info ] [MainThread]: os info: Linux-6.8.0-1021-azure-x86_64-with-glibc2.35
[0m11:31:09.266774 [info ] [MainThread]: Using profiles dir at /home/vscode/.dbt
[0m11:31:09.267487 [info ] [MainThread]: Using profiles.yml file at /home/vscode/.dbt/profiles.yml
[0m11:31:09.268064 [info ] [MainThread]: Using dbt_project.yml file at /workspaces/ae-club-louissa/dbt_project.yml
[0m11:31:09.268530 [info ] [MainThread]: adapter type: bigquery
[0m11:31:09.268966 [info ] [MainThread]: adapter version: 1.8.3
[0m11:31:09.269398 [info ] [MainThread]: Configuration:
[0m11:31:09.269806 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m11:31:09.270207 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m11:31:09.270602 [info ] [MainThread]: Required dependencies:
[0m11:31:09.271045 [debug] [MainThread]: Executing "git --help"
[0m11:31:09.273044 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:31:09.273561 [debug] [MainThread]: STDERR: "b''"
[0m11:31:09.274136 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:31:09.274719 [info ] [MainThread]: Connection:
[0m11:31:09.275372 [info ] [MainThread]:   method: oauth
[0m11:31:09.275828 [info ] [MainThread]:   database: aec-students
[0m11:31:09.276224 [info ] [MainThread]:   execution_project: aec-students
[0m11:31:09.276679 [info ] [MainThread]:   schema: dbt_louissa
[0m11:31:09.277086 [info ] [MainThread]:   location: US
[0m11:31:09.277472 [info ] [MainThread]:   priority: interactive
[0m11:31:09.277874 [info ] [MainThread]:   maximum_bytes_billed: None
[0m11:31:09.278249 [info ] [MainThread]:   impersonate_service_account: None
[0m11:31:09.278621 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m11:31:09.279056 [info ] [MainThread]:   job_retries: 1
[0m11:31:09.279440 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m11:31:09.279872 [info ] [MainThread]:   job_execution_timeout_seconds: 300
[0m11:31:09.280364 [info ] [MainThread]:   timeout_seconds: 300
[0m11:31:09.280805 [info ] [MainThread]:   client_id: None
[0m11:31:09.281296 [info ] [MainThread]:   token_uri: None
[0m11:31:09.281858 [info ] [MainThread]:   dataproc_region: None
[0m11:31:09.282373 [info ] [MainThread]:   dataproc_cluster_name: None
[0m11:31:09.282945 [info ] [MainThread]:   gcs_bucket: None
[0m11:31:09.283361 [info ] [MainThread]:   dataproc_batch: None
[0m11:31:09.284051 [info ] [MainThread]: Registered adapter: bigquery=1.8.3
[0m11:31:09.406839 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m11:31:09.407646 [debug] [MainThread]: Opening a new connection, currently in state init
[0m11:31:09.802410 [debug] [MainThread]: On debug: select 1 as id
[0m11:31:10.085602 [error] [MainThread]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=aec-students&j=bq:US:d20bc6e5-da4f-4312-b413-4e3ea8de1cac&page=queryresults
[0m11:31:10.086549 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m11:31:10.087107 [info ] [MainThread]: [31m2 checks failed:[0m
[0m11:31:10.087538 [info ] [MainThread]: Project loading failed for the following reason:
 project path </workspaces/ae-club-louissa/dbt_project.yml> not found

[0m11:31:10.087997 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  Caller does not have required permission to use project aec-students. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=aec-students and then retry. Propagation of the new permission may take a few minutes.

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m11:31:10.089318 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 2.1976702, "process_in_blocks": "205128", "process_kernel_time": 0.281276, "process_mem_max_rss": "199452", "process_out_blocks": "24", "process_user_time": 1.958076}
[0m11:31:10.090007 [debug] [MainThread]: Command `dbt debug` failed at 11:31:10.089902 after 2.20 seconds
[0m11:31:10.090408 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m11:31:10.090901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d0345f43e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d0331ca81c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d03313f06a0>]}
[0m11:31:10.091346 [debug] [MainThread]: Flushing usage events
[0m11:46:27.779561 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca7c98cbeb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca7c817c730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca7c817c790>]}


============================== 11:46:27.782198 | 8485b17e-c63b-48eb-bf46-4e2e7dacfef9 ==============================
[0m11:46:27.782198 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:46:27.782966 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:46:27.783832 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:46:27.784969 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.049088173, "process_in_blocks": "0", "process_kernel_time": 0.056936, "process_mem_max_rss": "85852", "process_out_blocks": "16", "process_user_time": 1.023863}
[0m11:46:27.785897 [debug] [MainThread]: Command `dbt run` failed at 11:46:27.785747 after 0.05 seconds
[0m11:46:27.786364 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca7c98cbeb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca7c817c730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ca7c817c0d0>]}
[0m11:46:27.786834 [debug] [MainThread]: Flushing usage events
[0m11:46:46.097254 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x710bba04beb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x710bb85bc7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x710bb85bc820>]}


============================== 11:46:46.099851 | 824f2c79-1a38-4b79-9ca0-41d2f4c46055 ==============================
[0m11:46:46.099851 [info ] [MainThread]: Running with dbt=1.8.9
[0m11:46:46.100528 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:46:46.101089 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-louissa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:46:46.101939 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.048130862, "process_in_blocks": "0", "process_kernel_time": 0.064947, "process_mem_max_rss": "85696", "process_out_blocks": "8", "process_user_time": 1.042153}
[0m11:46:46.102521 [debug] [MainThread]: Command `dbt run` failed at 11:46:46.102419 after 0.05 seconds
[0m11:46:46.102941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x710bba04beb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x710bb85bc7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x710bb85bc160>]}
[0m11:46:46.103337 [debug] [MainThread]: Flushing usage events
